-- supabase_seed.sql
-- This script contains all the necessary SQL statements to create and populate your database.
-- You can run this entire script in the Supabase SQL Editor.

-- 1. Create the 'products' table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name TEXT NOT NULL,
    price NUMERIC NOT NULL,
    duration TEXT,
    category TEXT NOT NULL CHECK (category IN ('pc', 'ios', 'android')),
    image_url TEXT,
    ai_hint TEXT,
    href TEXT UNIQUE NOT NULL,
    features JSONB,
    description TEXT,
    badge TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Create the 'courses' table
CREATE TABLE IF NOT EXISTS courses (
    id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    description TEXT,
    learning_objectives JSONB,
    modules JSONB,
    banner_url TEXT,
    banner_ai_hint TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Insert data into the 'products' table

-- PC Products
INSERT INTO products (name, price, duration, category, image_url, ai_hint, href, features, badge) VALUES
('Vnhax Frozen Key', 5, 'Day', 'pc', 'https://i.postimg.cc/j5QRy4fy/Vnhax-frozen-key.jpg', 'gaming character cinematic', '/products/vnhax-frozen-key', '["100% Safe & Secure", "Special Kill Effects", "Best Recoil Control", "ESP, Skins & Aimbot", "Integrated emulator bypass"]', NULL),
('Vnhax Week Key', 15, 'Week', 'pc', 'https://i.postimg.cc/26Mvsmyz/Vnhax-week-key.jpg', 'gaming character cinematic', '/products/vnhax-week-key', '["100% Safe & Secure", "Special Kill Effects", "Best Recoil Control", "ESP, Skins & Aimbot", "Integrated emulator bypass"]', NULL),
('Vnhax Month Key', 30, 'Month', 'pc', 'https://i.postimg.cc/cJ1bH7mv/Vnhax-month-key.jpg', 'gaming character cinematic', '/products/vnhax-month-key', '["100% Safe & Secure", "Special Kill Effects", "Best Recoil Control", "ESP, Skins & Aimbot", "Integrated emulator bypass"]', 'POPULAR!'),
('Vnhax Admin Key', 190, 'Lifetime', 'pc', 'https://i.postimg.cc/QdYpQpD9/Vnhax-Admin-key.jpg', 'gaming character cinematic', '/products/vnhax-admin-key', '["100% Safe & Secure", "Special Kill Effects", "Best Recoil Control", "ESP, Skins & Aimbot", "Integrated emulator bypass"]', '10% Discount'),
('Redeye Frozen Key', 5, 'Day', 'pc', 'https://i.postimg.cc/JhTnsWfj/Redeye-frozen-key.jpg', 'gaming character cinematic', '/products/redeye-frozen-key', '["Players, Bots & Airdrop ESP", "HWID Spoofer & Emulator Bypass", "Aimbot & Recoil Control", "Radar & Item Visuals", "24/7 Dedicated Support"]', NULL),
('Redeye Week Key', 15, 'Week', 'pc', 'https://i.postimg.cc/rwVMxPCj/Redeye-week-key.jpg', 'gaming character cinematic', '/products/redeye-week-key', '["Players, Bots & Airdrop ESP", "HWID Spoofer & Emulator Bypass", "Aimbot & Recoil Control", "Radar & Item Visuals", "24/7 Dedicated Support"]', NULL),
('Redeye Month Key', 30, 'Month', 'pc', 'https://i.postimg.cc/8PDSg03G/Redeye-month-key.jpg', 'gaming character cinematic', '/products/redeye-month-key', '["Players, Bots & Airdrop ESP", "HWID Spoofer & Emulator Bypass", "Aimbot & Recoil Control", "Radar & Item Visuals", "24/7 Dedicated Support"]', 'POPULAR!'),
('Anubis Week Key', 20, 'Week', 'pc', 'https://i.postimg.cc/3N60d0qM/Anubis-week-key.jpg', 'gaming character cinematic', '/products/anubis-week-key', '["Silent Aimbot", "Aimbot FOV value", "Draw FOV as Circle", "Skip Knocked Enemies", "Show Current Aim Position", "Draw Line to Target bone"]', NULL),
('Anubis Month Key', 40, 'Month', 'pc', 'https://i.postimg.cc/Gh8s6zBb/Anubis-month-key.jpg', 'gaming character cinematic', '/products/anubis-month-key', '["Silent Aimbot", "Aimbot FOV value", "Draw FOV as Circle", "Skip Knocked Enemies", "Show Current Aim Position", "Draw Line to Target bone"]', 'POPULAR!');

-- iOS Products
INSERT INTO products (name, price, duration, category, image_url, ai_hint, href, features, badge) VALUES
('Vnhax iOS Frozen Key', 5, 'Day', 'ios', 'https://i.postimg.cc/k4WLbYWy/vn-ios-frozen-key.jpg', 'gaming character cinematic', '/products/vnhax-ios-frozen-key', '["100% Safe & Secure", "Special Kill Effects", "Best Recoil Control", "ESP, Skins & Aimbot", "Radar & Item Visuals"]', NULL),
('Vnhax iOS Week Key', 15, 'Week', 'ios', 'https://i.postimg.cc/J404Fh2J/vn-ios-week-key.jpg', 'gaming character cinematic', '/products/vnhax-ios-week-key', '["100% Safe & Secure", "Special Kill Effects", "Best Recoil Control", "ESP, Skins & Aimbot", "Radar & Item Visuals"]', NULL),
('Vnhax iOS Month Key', 30, 'Month', 'ios', 'https://i.postimg.cc/yYGYCzMG/vn-ios-month-key.jpg', 'gaming character cinematic', '/products/vnhax-ios-month-key', '["100% Safe & Secure", "Special Kill Effects", "Best Recoil Control", "ESP, Skins & Aimbot", "Radar & Item Visuals"]', 'POPULAR!'),
('Star iOS Frozen Key', 5, 'Day', 'ios', 'https://i.postimg.cc/SxKT8Bjm/star-ios-frozen-key.jpg', 'gaming character cinematic', '/products/star-ios-frozen-key', '["Players, Bots & Airdrop ESP", "HWID Spoofer", "Aimbot & Recoil Control", "Radar & Item Visuals", "24/7 Dedicated Support"]', NULL),
('Star iOS Week Key', 15, 'Week', 'ios', 'https://i.postimg.cc/6pS0ZTDh/star-ios-week-key.jpg', 'gaming character cinematic', '/products/star-ios-week-key', '["Players, Bots & Airdrop ESP", "HWID Spoofer", "Aimbot & Recoil Control", "Radar & Item Visuals", "24/7 Dedicated Support"]', NULL),
('Star iOS Month Key', 30, 'Month', 'ios', 'https://i.postimg.cc/9Qq9vbnG/star-ios-month-key.jpg', 'gaming character cinematic', '/products/star-ios-month-key', '["Players, Bots & Airdrop ESP", "HWID Spoofer", "Aimbot & Recoil Control", "Radar & Item Visuals", "24/7 Dedicated Support"]', 'POPULAR!'),
('Tornado iOS Week Key', 17, 'Week', 'ios', 'https://i.postimg.cc/MpXs95F7/tornado-ios-week-key.jpg', 'gaming character cinematic', '/products/tornado-ios-week-key', '["Silent Aimbot", "Aimbot FOV Value", "Draw FOV as Circle", "Show Current Aim Position", "Skip Knocked Enemies", "Draw Line to Target Bone"]', NULL),
('Tornado iOS Month Key', 35, 'Month', 'ios', 'https://i.postimg.cc/KjJNN37p/tornado-ios-month-key.jpg', 'gaming character cinematic', '/products/tornado-ios-month-key', '["Silent Aimbot", "Aimbot FOV Value", "Draw FOV as Circle", "Show Current Aim Position", "Skip Knocked Enemies", "Draw Line to Target Bone"]', 'POPULAR!');

-- Android Products
INSERT INTO products (name, price, duration, category, image_url, ai_hint, href, features, badge) VALUES
('Shield Android Day Key', 5, 'Day', 'android', 'https://i.postimg.cc/GhjRky3C/SHIELD-Android-day-key.jpg', 'gaming character cinematic', '/products/shield-android-day-key', '["Players, Bots & Airdrop ESP", "FOV Circle & Show Aim Position", "Aimbot & Recoil Control", "Radar & Item Visuals", "24/7 Dedicated Support"]', NULL),
('Shield Android Week Key', 15, 'Week', 'android', 'https://i.postimg.cc/Gptb3mC1/SHIELD-Android-week-key.jpg', 'gaming character cinematic', '/products/shield-android-week-key', '["Players, Bots & Airdrop ESP", "FOV Circle & Show Aim Position", "Aimbot & Recoil Control", "Radar & Item Visuals", "24/7 Dedicated Support"]', NULL),
('Shield Android Month Key', 30, 'Month', 'android', 'https://i.postimg.cc/Hxj1mZbW/SHIELD-Android-month-key.jpg', 'gaming character cinematic', '/products/shield-android-month-key', '["Players, Bots & Airdrop ESP", "FOV Circle & Show Aim Position", "Aimbot & Recoil Control", "Radar & Item Visuals", "24/7 Dedicated Support"]', 'POPULAR!'),
('Zolo Android Day Key', 5, 'Day', 'android', 'https://i.postimg.cc/kGGfpL39/ZOLO-ios-day-key.jpg', 'gaming character cinematic', '/products/zolo-android-day-key', '["Radar & Visuals", "Aimbot FOV value", "Draw FOV as Circle", "Show Current Aim Position", "Skip Knocked Enemies", "Draw Line to Target bone"]', NULL),
('Zolo Android Week Key', 15, 'Week', 'android', 'https://i.postimg.cc/YStNPTYV/ZOLO-ios-month-key-1.jpg', 'gaming character cinematic', '/products/zolo-android-week-key', '["Radar & Visuals", "Aimbot FOV value", "Draw FOV as Circle", "Show Current Aim Position", "Skip Knocked Enemies", "Draw Line to Target bone"]', NULL),
('Zolo Android Month Key', 30, 'Month', 'android', 'https://i.postimg.cc/qBc3P1MH/ZOLO-ios-month-key.jpg', 'gaming character cinematic', '/products/zolo-android-month-key', '["Radar & Visuals", "Aimbot FOV value", "Draw FOV as Circle", "Show Current Aim Position", "Skip Knocked Enemies", "Draw Line to Target bone"]', 'POPULAR!'),
('Kernel Root Android Week Key', 20, 'Week', 'android', 'https://i.postimg.cc/NjV8sb9G/Kernel-Android-week-key.jpg', 'gaming character cinematic', '/products/kernel-android-week-key', '["Silent Aimbot + FOV", "FOV Circle & Aim Position", "ESP (Players, Bots, Airdrops)", "Recoil & Aimbot Control", "HWID Spoofer", "Radar & Visuals"]', NULL),
('Kernel Root Android Month Key', 40, 'Month', 'android', 'https://i.postimg.cc/C1Jz1LPC/Kernel-Android-month-key.jpg', 'gaming character cinematic', '/products/kernel-android-month-key', '["Silent Aimbot + FOV", "FOV Circle & Aim Position", "ESP (Players, Bots, Airdrops)", "Recoil & Aimbot Control", "HWID Spoofer", "Radar & Visuals"]', 'POPULAR!');

-- 4. Insert data into the 'courses' table
INSERT INTO courses (title, slug, description, learning_objectives, modules, banner_url, banner_ai_hint) VALUES
('Mastering CSS', 'css', 'Unlock the full potential of web styling with our comprehensive CSS course. From fundamentals to advanced animations, you will learn how to create beautiful and responsive websites.', '["Understand CSS syntax, selectors, and the cascade.", "Master the box model, positioning, and layout techniques.", "Learn Flexbox and Grid for modern, responsive designs.", "Create stunning animations and transitions.", "Apply best practices for writing clean and maintainable CSS.", "Explore advanced topics like variables and pre-processors."]', '[{"title": "Introduction to CSS", "description": "The basics of CSS and how it works with HTML."}, {"title": "Selectors and Specificity", "description": "Targeting elements with precision."}, {"title": "The Box Model", "description": "Understanding margins, padding, and borders."}, {"title": "Layouts with Flexbox", "description": "Building flexible and responsive layouts."}, {"title": "Advanced Grid Systems", "description": "Mastering two-dimensional layouts."}, {"title": "Transitions and Animations", "description": "Bringing your web pages to life."}]', 'https://picsum.photos/600/400', 'css code'),
('Advanced HTML5', 'html', 'Go beyond the basics and master the full power of HTML5. This course covers semantic markup, accessibility, multimedia integration, and modern APIs to build structured and meaningful web content.', '["Write clean, semantic, and accessible HTML.", "Integrate audio, video, and interactive elements.", "Understand and use the Canvas API for graphics.", "Work with modern form controls and validation.", "Learn about Web Storage, Geolocation, and other APIs.", "Optimize HTML for performance and SEO."]', '[{"title": "Semantic HTML", "description": "Structuring your content for meaning."}, {"title": "Multimedia Elements", "description": "Embedding audio and video."}, {"title": "Advanced Forms", "description": "Creating interactive and accessible forms."}, {"title": "Canvas and SVG", "description": "Drawing graphics on the web."}, {"title": "Web APIs", "description": "Using browser APIs like Geolocation and Web Storage."}, {"title": "Accessibility (a11y)", "description": "Making your websites usable for everyone."}]', 'https://picsum.photos/600/400', 'html code'),
('Generative AI Fundamentals', 'gen-ai', 'Dive into the fascinating world of Generative AI. Learn the principles behind large language models (LLMs), diffusion models for image generation, and how to build applications with them.', '["Understand the core concepts of generative models.", "Learn how LLMs like GPT work.", "Explore text generation, summarization, and translation.", "Understand image generation with models like DALL-E and Stable Diffusion.", "Learn prompt engineering techniques for better results.", "Build a simple generative AI application."]', '[{"title": "Introduction to Generative AI", "description": "What is it and why is it important?"}, {"title": "Large Language Models (LLMs)", "description": "The technology behind ChatGPT."}, {"title": "Prompt Engineering", "description": "Getting the most out of AI models."}, {"title": "Image Generation Models", "description": "Creating art and images from text."}, {"title": "Building with AI APIs", "description": "Integrating generative AI into your projects."}, {"title": "The Future of AI", "description": "Exploring the ethics and future trends."}]', 'https://picsum.photos/600/400', 'generative ai'),
('TikTok Content Creation Mastery', 'tiktok', 'Learn the secrets to creating viral content on TikTok. This course covers everything from finding trends and shooting engaging videos to mastering the algorithm and growing your audience.', '["Understand the TikTok algorithm and how to use it to your advantage.", "Identify and capitalize on viral trends.", "Master video shooting, editing, and effects within the app.", "Develop a content strategy that builds a loyal following.", "Collaborate with other creators and brands.", "Monetize your TikTok presence effectively."]', '[{"title": "Understanding the TikTok Ecosystem", "description": "Navigating the platform and its culture."}, {"title": "Content Strategy and Ideation", "description": "Planning your content for maximum impact."}, {"title": "Shooting and Editing Techniques", "description": "Creating high-quality, engaging videos."}, {"title": "Growth Hacking the Algorithm", "description": "Tips and tricks to go viral."}, {"title": "Monetization and Brand Deals", "description": "Turning your passion into a career."}]', 'https://picsum.photos/600/400', 'social media'),
('Shopify E-commerce Blueprint', 'shopify', 'Build a successful online store from scratch with Shopify. This course guides you through store setup, product sourcing, theme customization, marketing, and scaling your e-commerce business.', '["Set up and configure a Shopify store.", "Find and add winning products to your store.", "Customize your store theme to match your brand.", "Implement effective marketing and SEO strategies.", "Manage orders, shipping, and customer service.", "Analyze your store data to scale your business."]', '[{"title": "Getting Started with Shopify", "description": "Setting up your account and store."}, {"title": "Product and Collection Management", "description": "Sourcing and organizing your products."}, {"title": "Theme Customization and Branding", "description": "Creating a beautiful storefront."}, {"title": "Marketing and Sales Channels", "description": "Driving traffic and making sales."}, {"title": "Order Fulfillment and Customer Service", "description": "Managing the day-to-day operations."}, {"title": "Analytics and Scaling", "description": "Using data to grow your empire."}]', 'https://picsum.photos/600/400', 'ecommerce online'),
('Monetizing AI Skills', 'ai-money', 'Learn how to turn your AI knowledge into a profitable venture. This course covers freelancing, building AI-powered SaaS products, consulting, and creating content to monetize your expertise.', '["Identify profitable niches in the AI industry.", "Price your AI services and products effectively.", "Find clients and projects as an AI freelancer.", "Develop and launch a simple AI-powered SaaS application.", "Build a personal brand as an AI expert.", "Create and sell AI-related digital products or courses."]', '[{"title": "The AI Gold Rush", "description": "Opportunities for monetization in the AI space."}, {"title": "AI Freelancing and Consulting", "description": "Selling your skills to businesses."}, {"title": "Building and Selling AI SaaS", "description": "From idea to recurring revenue."}, {"title": "Creating AI-Powered Content", "description": "Monetizing your knowledge through content."}, {"title": "Marketing for AI Ventures", "description": "How to attract customers and clients."}, {"title": "Ethical Considerations", "description": "Building a sustainable and responsible AI business."}]', 'https://picsum.photos/600/400', 'ai money'),
('AI-Powered Coding', 'ai-coding', 'Supercharge your development workflow with AI tools. Learn how to use AI code assistants, generate code from prompts, debug with AI, and automate repetitive coding tasks to become a 10x developer.', '["Master AI code completion tools like GitHub Copilot.", "Write effective prompts to generate functional code.", "Use AI for code explanation, refactoring, and optimization.", "Leverage AI for automated testing and debugging.", "Integrate AI into your CI/CD pipeline.", "Understand the future of software development with AI."]', '[{"title": "Introduction to AI Code Assistants", "description": "Getting started with tools like Copilot."}, {"title": "Prompt-Driven Development", "description": "Generating code from natural language."}, {"title": "AI-Assisted Debugging", "description": "Finding and fixing bugs faster."}, {"title": "Code Refactoring and Optimization", "description": "Improving code quality with AI."}, {"title": "Automated Testing with AI", "description": "Generating test cases automatically."}, {"title": "The Future of AI in Software Engineering", "description": "What to expect next."}]', 'https://picsum.photos/600/400', 'ai code'),
('Deepseek: Advanced Search & Analysis', 'deepseek', 'Master the art of advanced search and data analysis with Deepseek. This course covers powerful query techniques, data extraction, pattern recognition, and leveraging AI for deep insights.', '["Construct complex search queries for precise results.", "Extract and structure data from unstructured sources.", "Use AI-powered tools for sentiment analysis and topic modeling.", "Identify trends and patterns in large datasets.", "Automate research and data gathering tasks.", "Apply your skills to business intelligence and research."]', '[{"title": "The Art of the Query", "description": "Beyond basic keyword searching."}, {"title": "Data Extraction Techniques", "description": "Scraping and parsing data from the web."}, {"title": "AI-Powered Text Analysis", "description": "Understanding text data at scale."}, {"title": "Pattern Recognition", "description": "Finding hidden insights in your data."}, {"title": "Automating Research Workflows", "description": "Building tools to gather information."}, {"title": "Practical Applications", "description": "Case studies in market research and OSINT."}]', 'https://picsum.photos/600/400', 'data analysis'),
('JavaScript: The Advanced Concepts', 'javascript', 'Move beyond the fundamentals and master the core concepts of JavaScript. This course dives deep into closures, promises, async/await, prototypes, and modern ES6+ features.', '["Gain a deep understanding of the JavaScript event loop.", "Master asynchronous programming with Promises and async/await.", "Understand closures, scope, and execution context.", "Learn about prototypal inheritance and object-oriented patterns.", "Work with modern data structures like Maps and Sets.", "Write clean, efficient, and modern JavaScript code."]', '[{"title": "Asynchronous JavaScript", "description": "Callbacks, Promises, and Async/Await."}, {"title": "Core Concepts", "description": "Closures, Scope, and Hoisting."}, {"title": "Object-Oriented JavaScript", "description": "Prototypes, Classes, and Inheritance."}, {"title": "Functional Programming", "description": "Immutability, Pure Functions, and Higher-Order Functions."}, {"title": "Modern ES6+ Features", "description": "Destructuring, Spread/Rest, and Modules."}, {"title": "JavaScript Engine and Runtime", "description": "How JavaScript works under the hood."}]', 'https://picsum.photos/600/400', 'javascript code'),
('Adobe After Effects for Beginners', 'after-effects', 'Bring your creative ideas to life with Adobe After Effects. This course will teach you the fundamentals of motion graphics and visual effects, from basic animations to complex compositions.', '["Navigate the After Effects interface and workflow.", "Create animations using keyframes, shapes, and text.", "Understand and apply visual effects and presets.", "Work with masks, mattes, and compositing techniques.", "Learn the basics of 3D space and camera movement.", "Render and export your projects for various platforms."]', '[{"title": "Getting Started", "description": "Understanding the workspace and basic tools."}, {"title": "Animation Principles", "description": "Bringing motion to life with keyframes."}, {"title": "Shape Layers and Text Animation", "description": "Creating dynamic graphic elements."}, {"title": "Visual Effects and Compositing", "description": "Adding magic to your videos."}, {"title": "Working in 3D Space", "description": "Creating depth and perspective."}, {"title": "Rendering and Exporting", "description": "Sharing your work with the world."}]', 'https://picsum.photos/600/400', 'motion graphics'),
('Adobe Premiere Pro Fundamentals', 'premiere-pro', 'Learn professional video editing with Adobe Premiere Pro. This course covers the entire workflow from importing footage and creating sequences to color correction, audio mixing, and exporting.', '["Master the Premiere Pro interface and editing tools.", "Organize and manage your media effectively.", "Learn cutting, trimming, and sequencing techniques.", "Apply transitions, effects, and color correction.", "Edit and mix audio like a pro.", "Export high-quality video for any platform."]', '[{"title": "Introduction to Premiere Pro", "description": "Navigating the workspace and importing media."}, {"title": "The Editing Workflow", "description": "From rough cut to fine cut."}, {"title": "Working with Audio", "description": "Mixing sound and adding music."}, {"title": "Color Correction and Grading", "description": "Creating a cinematic look."}, {"title": "Titles, Graphics, and Effects", "description": "Adding professional polish."}, {"title": "Exporting and Sharing", "description": "Delivering your final video."}]', 'https://picsum.photos/600/400', 'video editing');

-- End of script
